#+TITLE:unsoRted R package
#+AUTHOR: Johannes Rainer
#+email: johannes.rainer@i-med.ac.at
#+OPTIONS: ^:{}
#+INFOJS_OPT:
#+PROPERTY: exports code
#+PROPERTY: session *R*
#+PROPERTY: noweb yes
#+PROPERTY: results output
#+PROPERTY: tangle yes
#+STARTUP: overview
#+INFOJS_OPT: view:t toc:t ltoc:t mouse:underline buttons:0 path:http://thomasf.github.io/solarized-css/org-info.min.js
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://thomasf.github.io/solarized-css/solarized-light.min.css' />
#+LATEX_HEADER: \usepackage[backend=bibtex,style=chem-rsc,hyperref=true]{biblatex}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \setlength{\textwidth}{17.0cm}
#+LATEX_HEADER: \setlength{\hoffset}{-2.5cm}
#+LATEX_HEADER: \setlength{\textheight}{22cm}
#+LATEX_HEADER: \setlength{\voffset}{-1.5cm}
#+LATEX_HEADER: \addbibresource{~/Documents/Unison/Papers2/bib/references.bib}
#+LATEX_HEADER: \usepackage{verbatim}
#+LATEX_HEADER: \usepackage{inconsolata}
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \def\verbatim@font{\scriptsize\ttfamily}
#+LATEX_HEADER: \makeatother
-----

* Description

This R package contains some unsorted utilities and functions that might make life easier in the day-to-day use of R for data analysis.


** Functions related to data analysis

+ =getAnnotation=: retrieves an annotation data.frame for a given (Affymetrix based) =ExpressionSet=. For more informations see the according help.

+ =getAnnotationForIDs=: retrieves a data.frame with annotations for the provided feature (probe set) ids. For more informations see the according help.

+ =getRepPS=: returns a representative probe set for a gene based on some criteria. For more informations see the according help.

+ =hyperGGeneric=: performs a category analysis on any user provided definition of categories. For more informations see the according help.

** Other utilities

+ =convertTxt2Xls=: converts a text file with tabular content to a Microsoft Excel spreadsheet. For more informations see the according help.

+ =load.from.http=: loads a RData file from a remote server (e.g. http or ftp server). For more informations see the according help.

+ =pastedmatch=: value matching allowing e.g. =;= separated values. For more informations see the according help.

+ =read.table.from.http=: loads and reads a table from a remote (e.g. http or ftp) server. For more informations see the according help.


* Development

Please add new functions or improve existing ones. New functions should be documented (=Rd= format) and listed in this document (=README.org=) as well as in =man/unsoRted-package.Rd=. This file should then be exported as a markdown (=md=) file (best performed in Emacs org-mode =c-c c-e=).

** Authors

+ Daniel Bindreither
+ Johannes Rainer

(please add your name to this (=README.org=) file if you edit the code or add new functionality).

** TODOs

*** TODO File =annotation.R=, function =getAnnotation=: speed up the call.
*** TODO File =annotation.R=: implement annotations for our custom CDFs: automatically download them.

